const SECRET_VOICE_CATEGORY_NAME = "Secret voice channels";
const SECRET_TEXT_CATEGORY_NAME = "Secret text channels";
const SECRET_ROLE_PERMISSIONS = 9216;
const SECRET_ROLE_PREFIX = "SECRET";
module.exports = {
  SECRET_VOICE_CATEGORY_NAME,
  SECRET_TEXT_CATEGORY_NAME,
  SECRET_ROLE_PERMISSIONS,
  SECRET_ROLE_PREFIX,
};
